Document: inputattach
Title: Debian inputattach Manual
Author: <insert document author here>
Abstract: This manual describes what inputattach is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/inputattach/inputattach.sgml.gz

Format: postscript
Files: /usr/share/doc/inputattach/inputattach.ps.gz

Format: text
Files: /usr/share/doc/inputattach/inputattach.text.gz

Format: HTML
Index: /usr/share/doc/inputattach/html/index.html
Files: /usr/share/doc/inputattach/html/*.html
